spring.application.name=final-project

spring.datasource.url=jdbc:postgresql://localhost:5432/final_project_db
spring.datasource.username= postgres
spring.datasource.password= 12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=cpsc449-movie-list-secret-key-must-be-at-least-256-bits-long!
jwt.expiration=86400000
